//
//  QNTestConfig.h
//  QiniuSDK
//
//  Created by bailong on 14/10/7.
//  Copyright (c) 2014年 Qiniu. All rights reserved.
//

// 华东上传凭证
static NSString *const token_z0 = @"jH983zIUFIP1OVumiBVGeAfiLYJvwrF45S-t22eu:wS1tOlr_IyxMxZy2AVprHorZSWc=:eyJzY29wZSI6InpvbmUwLXNwYWNlIiwiZGVhZGxpbmUiOjE1OTYzMzU3NTUsICJyZXR1cm5Cb2R5Ijoie1wiZm9vXCI6JCh4OmZvbyksIFwiYmFyXCI6JCh4OmJhciksIFwibWltZVR5cGVcIjokKG1pbWVUeXBlKSwgXCJoYXNoXCI6JChldGFnKSwgXCJrZXlcIjokKGtleSl9In0=";
// 华北上传凭证
static NSString *const token_z1 = @"jH983zIUFIP1OVumiBVGeAfiLYJvwrF45S-t22eu:Mio6uWUUCsll3Rox3yC2MnwaTg8=:eyJzY29wZSI6InpvbmUxLXNwYWNlIiwiZGVhZGxpbmUiOjE1OTYzMzU3NTUsICJyZXR1cm5Cb2R5Ijoie1wiZm9vXCI6JCh4OmZvbyksIFwiYmFyXCI6JCh4OmJhciksIFwibWltZVR5cGVcIjokKG1pbWVUeXBlKSwgXCJoYXNoXCI6JChldGFnKSwgXCJrZXlcIjokKGtleSl9In0=";
// 华南上传凭证
static NSString *const token_z2 = @"jH983zIUFIP1OVumiBVGeAfiLYJvwrF45S-t22eu:hzTpUuXIWRxQOepwvCpXAMrzekA=:eyJzY29wZSI6InpvbmUyLXNwYWNlIiwiZGVhZGxpbmUiOjE1OTYzMzU3NTUsICJyZXR1cm5Cb2R5Ijoie1wiZm9vXCI6JCh4OmZvbyksIFwiYmFyXCI6JCh4OmJhciksIFwibWltZVR5cGVcIjokKG1pbWVUeXBlKSwgXCJoYXNoXCI6JChldGFnKSwgXCJrZXlcIjokKGtleSl9In0=";
// 北美上传凭证
static NSString *const token_na0 = @"jH983zIUFIP1OVumiBVGeAfiLYJvwrF45S-t22eu:tn8ve-oKLVqgz5tM_E_gFsxyuwk=:eyJzY29wZSI6InpvbmUtbmEwLXNwYWNlIiwiZGVhZGxpbmUiOjE1OTYzMzU3NTUsICJyZXR1cm5Cb2R5Ijoie1wiZm9vXCI6JCh4OmZvbyksIFwiYmFyXCI6JCh4OmJhciksIFwibWltZVR5cGVcIjokKG1pbWVUeXBlKSwgXCJoYXNoXCI6JChldGFnKSwgXCJrZXlcIjokKGtleSl9In0=";
// 东南亚上传凭证
static NSString *const token_as0 = @"jH983zIUFIP1OVumiBVGeAfiLYJvwrF45S-t22eu:QLkQsbXedUirvDJf9EBEdZQDcJE=:eyJzY29wZSI6InpvbmUtYXMwLXNwYWNlIiwiZGVhZGxpbmUiOjE1OTYzMzU3NTUsICJyZXR1cm5Cb2R5Ijoie1wiZm9vXCI6JCh4OmZvbyksIFwiYmFyXCI6JCh4OmJhciksIFwibWltZVR5cGVcIjokKG1pbWVUeXBlKSwgXCJoYXNoXCI6JChldGFnKSwgXCJrZXlcIjokKGtleSl9In0=";
static NSString *const invalidBucketToken = @"jH983zIUFIP1OVumiBVGeAfiLYJvwrF45S-t22eu:pKkKCUzBFJQswoEQJ-xriFv2wxk=:eyJzY29wZSI6InpvbmVfaW52YWxpZCIsImRlYWRsaW5lIjoxNTk2MzM1NzU1LCAicmV0dXJuQm9keSI6IntcImZvb1wiOiQoeDpmb28pLCBcImJhclwiOiQoeDpiYXIpLCBcIm1pbWVUeXBlXCI6JChtaW1lVHlwZSksIFwiaGFzaFwiOiQoZXRhZyksIFwia2V5XCI6JChrZXkpfSJ9";
