# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QiniuDemoSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Qiniu', :path => '../'
  pod 'ZLPhotoBrowser'
  
  # Pods for QiniuDemoSwift

  target 'QiniuDemoSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QiniuDemoSwiftUITests' do
    # Pods for testing
  end

end
