source 'https://github.com/CocoaPods/Specs.git'

target "QiniuDemo" do
  platform :ios, "10.0"

#  pod 'Qiniu', '~> 7.4.0'
#  pod 'Qiniu', '7.1.7'
  pod 'Qiniu',:path => '../'
  pod 'HappyDNS',:path => '../../happy-dns-objc'
end

target "QiniuDemoTests" do
#  platform :ios, "7.0"
#  pod 'Qiniu',:path => '../'
end
