source 'https://github.com/CocoaPods/Specs.git'

target "QiniuDemo" do
  platform :ios, "6.0"
  pod 'Qiniu',:path => '../'
end

target "QiniuDemoTests" do
  platform :ios, "6.0"
  pod 'Qiniu',:path => '../'
end
